spring:
  jpa:
    hibernate:
      ddl-auto: validate
  output:
    ansi:
      enabled: detect
  main:
    banner-mode: log
  application:
    name: measure-report-service
server:
  port: 8090
db_host: localhost

#validate:
#  measurereport:
#    create: true
#    update: true

---
spring:
  profiles: local
  datasource:
    url: 'jdbc:mysql://${db_host}/measure_report_service?createDatabaseIfNotExist=true'
    username: root
    password: secret
logging:
#  level.org.hibernate.SQL: trace
#  level.org.hibernate.type.descriptor.sql: trace
#  level.org.springframework.web.client.RestTemplate: debug
#  level.org.springframework.transaction.interceptor: trace

#  This class changes depending on what implementation of PlatformTransactionManager is used)
#  level.org.springframework.orm.jpa.JpaTransactionManager: trace


security:
  user:
    password: 'secret'
server:
  port: 8090
---
security:
  user:
    password: 'secret'
spring:
  profiles: test
  datasource:
      url: 'jdbc:h2:mem:test;MODE=MySQL'
      username: root
      password: secret




